server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Toutes les routes inconnues renvoient index.html
    # C'est React Router qui gère ensuite la navigation côté client
    location / {
        try_files $uri $uri/ /index.html;
    }
}